const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const ts = require('typescript');
const source = fs.readFileSync(path.join(__dirname, '../src/app/shared/chart-time.ts'), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } });
const scope = { exports: {}, Intl, Date };
vm.runInNewContext(compiled.outputText, scope);
const {formatChartTime, formatChartTick, chartDate} = scope.exports;
const open = Date.parse('2026-09-21T03:45:00Z') / 1000;
assert.match(formatChartTime(open), /09:15 IST$/);
assert.equal(formatChartTick(open, 3), '09:15');
assert.equal(chartDate(open).getTime(), open * 1000, 'Formatting must not shift the original timestamp');
assert.equal(formatChartTime('2026-09-21'), formatChartTime({year:2026,month:9,day:21}));
assert.doesNotMatch(formatChartTime('2026-09-21'), /IST|00:00/);
assert.match(formatChartTime(Date.parse('2026-09-20T20:00:00Z')/1000), /^21 .*01:30 IST$/);
assert.match(formatChartTick(open, 0), /2026/);
console.log('PASS: IST market open, midnight rollover, daily calendar dates, and unchanged UTC timestamps.');
