const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../src/app/shared/chart-indicators.ts'), 'utf8');
const scope = { exports: {} };
vm.runInNewContext(ts.transpileModule(source, {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText, scope);
const {calculateStudy, STUDIES} = scope.exports;
const rows = Array.from({length:60}, (_,i) => ({time:1726803900+i*60,open:i+1,high:i+2,low:i,close:i+1,volume:100}));
const calc = (kind, data=rows, period=3) => calculateStudy(data,{kind,period,id:1,color:'#fff'});
const near = (a,b) => assert.ok(Math.abs(a-b)<1e-8, `${a} != ${b}`);
near(calc('SMA').values[0][2],2);
near(calc('EMA').values[0][3],3);
near(calc('WMA').values[0][2],14/6);
near(calc('Bollinger').values[1][2],2+2*Math.sqrt(2/3));
near(calc('Donchian').values[0][2],4);
near(calc('Donchian').values[1][2],0);
assert.ok(Number.isNaN(calc('RSI').values[0][2]));
near(calc('RSI').values[0][3],100);
near(calc('RSI',rows.map(r=>({...r,close:5}))).values[0][4],50);
near(calc('ATR').values[0][2],2);
near(calc('CCI').values[0][2],100);
near(calc('Stochastic').values[0][2],75);
near(calc('ROC').values[0][3],300);
near(calc('OBV').values[0][4],400);
near(calc('MACD').values[0][40],7);
near(calc('MACD').values[1][40],7);
near(calc('MACD').values[2][40],0);
near(calc('VWAP').values[0][2],2);
const tomorrow = {...rows[3],time:rows[0].time+86400,close:10,high:11,low:9};
near(calc('VWAP',[...rows.slice(0,3),tomorrow]).values[0][3],10);
assert.ok(calc('Volume',rows.map(({volume,...r})=>r)).values[0].every(Number.isNaN));
assert.ok(Number.isNaN(calc('Volume',[{...rows[0],volumeComplete:false}]).values[0][0]));
assert.ok(Number.isNaN(calc('VWAP',[rows[0],{...rows[1],volumeComplete:false},rows[2]]).values[0][2]));
for (const {kind} of STUDIES) {
  assert.equal(calc(kind).values[0].length,rows.length);
  assert.equal(calc(kind,[]).values[0].length,0);
  const changed = rows.map((r,i)=>i===59?{...r,close:100,high:101}:r);
  const before=calc(kind).values, after=calc(kind,changed).values;
  for(let j=0;j<before.length;j++) assert.deepEqual(Array.from(before[j].slice(0,-1)),Array.from(after[j].slice(0,-1)),kind+' must not repaint earlier values');
}
console.log('PASS: 14 indicators, warm-up, reference values, VWAP session reset, missing volume, no lookahead.');
