const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../src/app/shared/live-candles.ts'), 'utf8');
const compiled = ts.transpileModule(source, {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}});
const scope = {exports:{}};
vm.runInNewContext(compiled.outputText,scope);
const merge=scope.exports.liveCandles;
const history=[{time:300,open:100,high:110,low:90,close:105}];
const ticks=[{time:300,open:106,high:120,low:95,close:115,last_tick:550}, {time:600,open:116,high:117,low:116,close:117,last_tick:610}];
const result=merge(history,ticks,500);
assert.equal(result.length,2);
assert.equal(result[0].open,100);
assert.equal(result[0].high,120);
assert.equal(result[0].low,90);
assert.equal(result[0].close,115);
assert.equal(history[0].close,105);
assert.equal(merge(history,ticks,560)[0].close,105,'Historical refresh must not regress to an older tick');
assert.equal(merge(history,[{...ticks[0],time:0}],0).length,1,'Ignore old initial snapshots');
console.log('PASS: streamed OHLC merge, rollover, history refresh ordering and immutability');
