const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../src/app/shared/percentage-change.ts'), 'utf8');
const scope = {exports:{}};
vm.runInNewContext(ts.transpileModule(source, {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,scope);
const { percentageChange: pct, formatPercentage: format, chartChange } = scope.exports;
assert.equal(pct(120,100),20);
assert.equal(pct(80,100),-20);
for (const ref of [0,-1,null,NaN,Infinity]) assert.equal(pct(100,ref),null);
assert.equal(format(-0.0001),'0.00%');
assert.equal(format(20),'+20.00%');
assert.equal(format(null),'—');
const rows = [{time:'2026-09-25',open:80,close:100},{time:'2026-09-28',open:105,close:110},{time:'2026-09-29',open:110,close:99}];
assert.equal(chartChange(rows,rows[1]).percent,10);
assert.equal(chartChange(rows,rows[2]).percent,-10);
assert.equal(chartChange(rows,rows[0]).label,'vs open');
assert.equal(chartChange(rows,{...rows[1],time:{year:2026,month:9,day:28}}).percent,10);
assert.equal(chartChange([{time:1000,close:100},{time:1300,close:102}],{time:1300,close:103}).percent,3);
assert.equal(chartChange([{time:1000,value:100},{time:1300,value:120}],{time:1300,value:120},true).percent,20);
assert.equal(chartChange([{time:1000,value:0}],{time:1000,value:0},true),null);
console.log('PASS: percentage signs, missing/zero references, candle gaps, hover dates, live candles and area charts');
