const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../src/app/shared/portfolio-totals.ts'), 'utf8');
const compiled = ts.transpileModule(source, {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}});
const scope = {exports:{}};
vm.runInNewContext(compiled.outputText,scope);
const totals = scope.exports.portfolioTotals;
const holding = {quantity:10,t1_quantity:2,used_quantity:5,collateral_quantity:4,average_price:100,last_price:110,pnl:120};
const result = totals([holding],[{quantity:-1,pnl:-50},{quantity:0,pnl:20}]);
assert.equal(result.invested,1200,'Sold and pledged quantities must not be subtracted or added again');
assert.equal(result.current,1320);
assert.equal(result.pnl,120);
assert.equal(result.positionsPnl,-30,'Include closed positions in broker positions total');
assert.equal(totals([{...holding,mtf:{quantity:3,average_price:90}}],[]).invested,1470);
assert.equal(totals([{...holding,mtf:{quantity:3,average_price:90}}],[]).current,1650);
assert.equal(totals([{...holding,average_price:null}],[]).invested,null);
assert.equal(totals([{...holding,discrepancy:true}],[]).invested,null);
assert.equal(totals([{...holding,pnl:null}],[]).pnl,null);
assert.equal(totals([{...holding,last_price:NaN}],[]).current,null);
assert.equal(totals([],[]).invested,0);
assert.equal(totals([],[]).pnl,0);
console.log('PASS: holdings and positions totals, T1/MTF, sold/pledged units, incomplete and empty snapshots');
