const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../src/app/shared/portfolio-live.ts'), 'utf8');
const scope = {exports:{}};
vm.runInNewContext(ts.transpileModule(source, {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText, scope);
const live = scope.exports.livePortfolio;
const at = Date.parse('2026-09-29T04:30:00Z')/1000;
const base = {fetched_at:new Date(at*1000).toISOString(), holdings:[{instrument_token:1,quantity:10,t1_quantity:2,mtf:{quantity:3},last_price:100,average_price:80,pnl:300}], positions:[{instrument_token:1,quantity:-2,multiplier:10,last_price:100,pnl:50,unrealised:40},{instrument_token:1,quantity:0,multiplier:1,last_price:100,pnl:12}]};
const feed = price => ({server_time:at+5,quotes:{1:{price,time:at+1}}});
let updated = live(base, feed(110));
assert.equal(updated.holdings[0].pnl,450);
assert.equal(updated.holdings[0].last_price,110);
assert.equal(updated.holdings[0].average_price,80);
assert.equal(updated.positions[0].pnl,-150);
assert.equal(updated.positions[0].unrealised,-160);
assert.equal(updated.positions[1],base.positions[1]);
assert.equal(base.holdings[0].last_price,100, 'Never mutate the broker baseline');
assert.equal(live(base,feed(120)).holdings[0].pnl,600, 'Each tick applies one delta from the baseline');
assert.equal(live(base, {server_time:at+5,quotes:{1:{price:120,time:at-1}}}).holdings[0],base.holdings[0], 'Ignore cached ticks older than the new snapshot');
assert.equal(live(base, {server_time:at+5,quotes:{1:{price:120,time:at+60}}}).holdings[0],base.holdings[0]);
assert.equal(live(base, feed(NaN)).holdings[0],base.holdings[0]);
assert.equal(live({...base,positions:[{...base.positions[0],multiplier:null}]},feed(110)).positions[0].pnl,null);
assert.equal(live({...base,holdings:[{...base.holdings[0],pnl:null}]},feed(110)).holdings[0].pnl,null);
assert.equal(live({...base,holdings:[{...base.holdings[0],instrument_token:2}]},feed(110)).holdings[0].last_price,100);
assert.ok(Math.abs(live({...base,holdings:[{...base.holdings[0],last_price:110,day_change_percentage:10}]},feed(120)).holdings[0].day_change_percentage - 20) < 1e-9);
assert.equal(live(base,feed(120)).holdings[0].day_change_percentage,undefined);
console.log('PASS: live holdings, T1/MTF, short positions/multipliers, realized P&L, freshness, baseline isolation');
